-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE Cliente (
id_cliente SERIAL PRIMARY KEY,
CPF_CLIENTE VARCHAR(14) NOT NULL,
NOME_CLIENTE VARCHAR(50),
CEL_CLIENTE VARCHAR(15)
);

CREATE TABLE PRODUTO (
ID_PRODUTO DECIMAL PRIMARY KEY,
VALOR_PRODUTO DECIMAL NOT NULL,
QTDE INT
);

-- tabela compra
CREATE TABLE COMPRA (
ID_PEDIDO SERIAL PRIMARY KEY,
DATA_COMPRA_PRODUTO DATE,
ID_PRODUTO DECIMAL,
id_cliente int,
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO (ID_PRODUTO),
FOREIGN KEY(ID_CLIENTE) REFERENCES cliente (ID_CLIENTE)/*falha: chave estrangeira*/
);

-- visualizar as informacoes
select * from cliente, produto

 